var annotated =
[
    [ "CSFacebookParameter", "interface_c_s_facebook_parameter.html", "interface_c_s_facebook_parameter" ],
    [ "CSSocial", "interface_c_s_social.html", "interface_c_s_social" ],
    [ "<CSSocialManagerDataSource>", "protocol_c_s_social_manager_data_source-p.html", "protocol_c_s_social_manager_data_source-p" ],
    [ "CSSocialParameter", "interface_c_s_social_parameter.html", "interface_c_s_social_parameter" ],
    [ "<CSSocialParameter>", "protocol_c_s_social_parameter-p.html", "protocol_c_s_social_parameter-p" ],
    [ "CSSocialRequest", "interface_c_s_social_request.html", "interface_c_s_social_request" ],
    [ "CSSocialRequestFacebook", "interface_c_s_social_request_facebook.html", "interface_c_s_social_request_facebook" ],
    [ "CSSocialRequestFacebookFriends", "interface_c_s_social_request_facebook_friends.html", null ],
    [ "CSSocialRequestFacebookFriendsPaging", "interface_c_s_social_request_facebook_friends_paging.html", null ],
    [ "CSSocialRequestFacebookGetUserImage", "interface_c_s_social_request_facebook_get_user_image.html", null ],
    [ "CSSocialRequestFacebookPostPhoto", "interface_c_s_social_request_facebook_post_photo.html", null ],
    [ "CSSocialRequestFacebookPostWall", "interface_c_s_social_request_facebook_post_wall.html", null ],
    [ "CSSocialRequestFacebookUser", "interface_c_s_social_request_facebook_user.html", null ],
    [ "CSSocialRequestGoogle", "interface_c_s_social_request_google.html", null ],
    [ "CSSocialRequestTwitter", "interface_c_s_social_request_twitter.html", null ],
    [ "CSSocialRequestTwitterFriends", "interface_c_s_social_request_twitter_friends.html", null ],
    [ "CSSocialRequestTwitterGetUserImage", "interface_c_s_social_request_twitter_get_user_image.html", null ],
    [ "CSSocialRequestTwitterMessage", "interface_c_s_social_request_twitter_message.html", null ],
    [ "CSSocialService", "interface_c_s_social_service.html", "interface_c_s_social_service" ],
    [ "<CSSocialService>", "protocol_c_s_social_service-p.html", "protocol_c_s_social_service-p" ],
    [ "CSSocialServiceFacebook", "interface_c_s_social_service_facebook.html", null ],
    [ "CSSocialServiceFacebook(Helper)", "category_c_s_social_service_facebook_07_helper_08.html", "category_c_s_social_service_facebook_07_helper_08" ],
    [ "CSSocialServiceGoogle", "interface_c_s_social_service_google.html", null ],
    [ "CSSocialServiceTwitter", "interface_c_s_social_service_twitter.html", null ],
    [ "CSSocialServiceTwitter(Helper)", "category_c_s_social_service_twitter_07_helper_08.html", "category_c_s_social_service_twitter_07_helper_08" ],
    [ "CSSocialUser", "interface_c_s_social_user.html", "interface_c_s_social_user" ],
    [ "<CSSocialUser>", "protocol_c_s_social_user-p.html", "protocol_c_s_social_user-p" ],
    [ "CSSocialUserFacebook", "interface_c_s_social_user_facebook.html", null ],
    [ "CSSocialUserTwitter", "interface_c_s_social_user_twitter.html", null ],
    [ "CSTwitteriOS4Plugin", "interface_c_s_twitteri_o_s4_plugin.html", null ],
    [ "CSTwitteriOS5Plugin", "interface_c_s_twitteri_o_s5_plugin.html", "interface_c_s_twitteri_o_s5_plugin" ],
    [ "CSTwitteriOS6Plugin", "interface_c_s_twitteri_o_s6_plugin.html", null ],
    [ "CSTwitterParameter", "interface_c_s_twitter_parameter.html", "interface_c_s_twitter_parameter" ],
    [ "CSTwitterPlugin", "interface_c_s_twitter_plugin.html", "interface_c_s_twitter_plugin" ],
    [ "<CSTwitterPlugin>", "protocol_c_s_twitter_plugin-p.html", "protocol_c_s_twitter_plugin-p" ]
];